### ISSUE TITLE
对数据库原理比较好奇，主语言又是java，只有h2 database 最符合学习需求了，不知和你开始的想法是否一致呢

### ISSUE THREAD

**Issue by nixub** [codefollower/H2-Research#19]

**Comment by codefollower** [comment]
建议你直接看 lealone 的代码吧，h2 已经很复杂了，复杂是复杂，但性能和设计做得都不如 lealone 了，lealone 的代码量也比 h2 少了将近一半了。

[H2-Research](https://github.com/codefollower/H2-Research) 这个研究项目我也停更一年多了，后续也不更新了，h2 对我已经没有研究价值了。

**Comment by nixub** [comment]
好的，不过你这个项目有点低调了，先来个star ，国产做数据库的貌似很少，这个项目你一个人开发的吗
